---
# ArgoCD Application for Vault
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.27.0"
    helm:
      releaseName: vault
      values: |
        server:
          dataStorage:
            size: 10Gi
          auditStorage:
            size: 10Gi
          ha:
            enabled: true
            replicas: 3
          
          serviceAccount:
            create: true
            name: vault
          
          ha:
            raft:
              enabled: true
              setNodeId: true
          
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
        
        ui:
          enabled: true
        
        csi:
          enabled: false  # Enable if using CSI driver for mounting secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
