---
# Example: Using Vault Agent Injector annotations
# This deployment will automatically inject secrets via Vault Agent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-agent-injector
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-agent
  template:
    metadata:
      labels:
        app: demo-app-agent
      annotations:
        # Enable Vault agent injection
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "application"
        
        # Inject database credentials
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/databases/postgres"
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/data/databases/postgres" -}}
          export DB_HOST="{{ .Data.data.host }}"
          export DB_PORT="{{ .Data.data.port }}"
          export DB_USER="{{ .Data.data.username }}"
          export DB_PASSWORD="{{ .Data.data.password }}"
          export DB_NAME="{{ .Data.data.database }}"
          {{- end }}
        
        # Inject application secrets
        vault.hashicorp.com/agent-inject-secret-app: "secret/data/applications/demo-app"
        vault.hashicorp.com/agent-inject-template-app: |
          {{- with secret "secret/data/applications/demo-app" -}}
          export APP_USERNAME="{{ .Data.data.username }}"
          export APP_PASSWORD="{{ .Data.data.password }}"
          export API_KEY="{{ .Data.data.api_key }}"
          {{- end }}
        
        # Inject as files instead of environment variables
        vault.hashicorp.com/agent-inject-file-config: "secret/data/applications/demo-app"
        vault.hashicorp.com/agent-inject-file-template-config: |
          {{- with secret "secret/data/applications/demo-app" -}}
          {
            "username": "{{ .Data.data.username }}",
            "password": "{{ .Data.data.password }}",
            "api_key": "{{ .Data.data.api_key }}"
          }
          {{- end }}
    spec:
      serviceAccountName: demo-app-sa
      containers:
      - name: app
        image: myapp:latest
        volumeMounts:
        - name: vault-token
          mountPath: /vault/secrets
        ports:
        - containerPort: 8080
      volumes:
      - name: vault-token
        emptyDir:
          medium: Memory
---
# ServiceAccount for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-sa
  namespace: production
