---
# Multi-cluster setup example
# Shows how to manage secrets across multiple Kubernetes clusters

# For Cluster 1 (Primary)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster1
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes-cluster1"
          role: "external-secrets-operator"
          serviceAccountRef:
            name: external-secrets-vault-auth
            namespace: external-secrets
---
# For Cluster 2 (Secondary)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster2
spec:
  provider:
    vault:
      server: "https://vault-dr.external.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes-cluster2"
          role: "external-secrets-operator"
          serviceAccountRef:
            name: external-secrets-vault-auth
            namespace: external-secrets
---
# Example: ExternalSecret using cluster-specific store
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: multi-cluster-app-secret
  namespace: production
spec:
  secretStoreRef:
    name: vault-backend-cluster1
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: applications/multi-cluster-app/production
      property: api_key
  - secretKey: database-url
    remoteRef:
      key: databases/postgres-prod
      property: url
---
# Failover example using ApplicationSet
# Deploys to different cluster based on conditions
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: failover-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: primary
        secretStore: vault-backend-cluster1
        weight: 100
      - cluster: secondary
        secretStore: vault-backend-cluster2
        weight: 0
  template:
    metadata:
      name: app-{{cluster}}
    spec:
      project: default
      source:
        repoURL: https://your-git-repo.com/apps
        path: app/{{cluster}}
        targetRevision: main
      destination:
        name: {{cluster}}
        namespace: production
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
