---
# Example: ExternalSecret in production namespace
# This will sync a secret from Vault to Kubernetes
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: applications/demo-app
      property: username
  - secretKey: password
    remoteRef:
      key: applications/demo-app
      property: password
  - secretKey: api_key
    remoteRef:
      key: applications/demo-app
      property: api_key
---
# Example: ExternalSecret for database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: production
spec:
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: "{{ .host }}"
        POSTGRES_PORT: "{{ .port }}"
        POSTGRES_DB: "{{ .database }}"
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
  data:
  - secretKey: host
    remoteRef:
      key: databases/postgres
      property: host
  - secretKey: port
    remoteRef:
      key: databases/postgres
      property: port
  - secretKey: username
    remoteRef:
      key: databases/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: databases/postgres
      property: password
  - secretKey: database
    remoteRef:
      key: databases/postgres
      property: database
---
# Example: Deployment using the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: app
        image: myapp:latest
        env:
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: username
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8080
