---
# Sample ExternalSecret for staging namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: applications/demo-app
      property: username
  - secretKey: password
    remoteRef:
      key: applications/demo-app
      property: password
  - secretKey: api_key
    remoteRef:
      key: applications/demo-app
      property: api_key
