---
# PodSecurityPolicy for Vault
# Ensures Vault runs with restricted security context
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: vault-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  allowedCapabilities:
  - IPC_LOCK  # Required by Vault to prevent memory swapping
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
    ranges:
    - min: 100
      max: 1000
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 2000
  seLinux:
    rule: 'MustRunAs'
    seLinuxOptions:
      level: 's0:c123,c456'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 2000
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 2000
  readOnlyRootFilesystem: false
---
# ClusterRole for PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - vault-psp
---
# ClusterRoleBinding for PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-psp
subjects:
- kind: ServiceAccount
  name: vault
  namespace: vault
