---
# ServiceAccount for Vault authentication from External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault-auth
  namespace: external-secrets
---
# ClusterRole for reading secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-vault-auth
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-vault-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-vault-auth
subjects:
- kind: ServiceAccount
  name: external-secrets-vault-auth
  namespace: external-secrets
