---
# SecretStore for connecting External Secrets Operator to Vault
# This SecretStore uses Kubernetes Service Account for authentication
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-operator"
          serviceAccountRef:
            name: external-secrets-vault-auth
      caBundle: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
---
# ClusterSecretStore - Available across all namespaces
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-operator"
          serviceAccountRef:
            name: external-secrets-vault-auth
            namespace: external-secrets
      caBundle: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
